### ISSUE TITLE
Task: add support for init programs, and spawn dependencies

### ISSUE THREAD

**Issue by sbstp** [sbstp/supermon#2]
```yaml
apps:
  init:
    exec: /usr/bin/init-stuff
    restart: OnFailure
  db:
    exec: /usr/bin/postgres
    after:
      - init
```
